### ISSUE TITLE
npm run algolia if (err) throw err

### ISSUE THREAD

**Issue by yudyananda** [chrisdmacrae/atomic-algolia#10]
Hi 

I'm usiing Hugo & windows

Here is my package.json
```json
{
  "name": "yes",
  "version": "1.0.0",
  "description": "build xxx.com",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "algolia": "atomic-algolia"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "keywords": [
    "blog"
  ],
  "author": "yudy ananda",
  "license": "MIT",
  "bugs": {
    "url": ""
  },
  "homepage": "",
  "devDependencies": {
    "atomic-algolia": "^0.3.11",
    "gulp": "^3.9.1",
    "gulp-clean-css": "^3.9.2",
    "gulp-css-purge": "^3.0.3",
    "gulp-html-prettify": "0.0.1",
    "gulp-minify-inline": "^1.0.0",
    "gulp-remove-empty-lines": "^0.1.0"
  },
  "dependencies": {
    
  }
}
```
I'm not sure what's wrong but `npm run algolia` throw me an error

```
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Yudy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'algolia' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose run-script [ 'prealgolia', 'algolia', 'postalgolia' ]
5 info lifecycle yes@1.0.0~prealgolia: yes@1.0.0
6 info lifecycle yes@1.0.0~algolia: yes@1.0.0
7 verbose lifecycle yes@1.0.0~algolia: unsafe-perm in lifecycle true
8 verbose lifecycle yes@1.0.0~algolia: PATH: C:\Users\Yudy\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\YUDY\WEB PROJECT\TIA\PROD\mm\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Python34\;C:\Python34\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Python36;C:\Python36\Scripts;C:\Program Files\Git\cmd;C:\Go\bin;C:\Hugo\bin;C:\cygwin64\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files (x86)\Common Files\Apple\Internet Services\;C:\Program Files\wkhtmltopdf\bin\;C:\filemanager\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Ruby24-x64\bin;C:\Users\Yudy\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Yudy\AppData\Local\atom\bin;C:\Users\Yudy\AppData\Roaming\npm;C:\Users\Yudy\AppData\Local\GitHubDesktop\bin;C:\Users\Yudy\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\Yarn\bin;C:\xampp\mysql\bin;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\HashiCorp\Vagrant\bin;%SUBLIMEHOME%;C:\Ruby24-x64\bin;C:\Users\Yudy\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Yudy\AppData\Local\atom\bin;C:\Users\Yudy\AppData\Local\GitHubDesktop\bin;C:\Users\Yudy\AppData\Roaming\Composer\vendor\bin;C:\Users\Yudy\AppData\Local\Yarn\bin;C:\Users\Yudy\AppData\Roaming\npm;C:\Program Files\Sublime Text 3;C:\Program Files (x86)\OpenShift;C:\Program Files\Heroku\bin
9 verbose lifecycle yes@1.0.0~algolia: CWD: E:\YUDY\WEB PROJECT\TIA\PROD\mm
10 silly lifecycle yes@1.0.0~algolia: Args: [ '/d /s /c', 'atomic-algolia' ]
11 silly lifecycle yes@1.0.0~algolia: Returned: code: 1  signal: null
12 info lifecycle yes@1.0.0~algolia: Failed to exec algolia script
13 verbose stack Error: yes@1.0.0 algolia: `atomic-algolia`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Yudy\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Yudy\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid yes@1.0.0
15 verbose cwd E:\YUDY\WEB PROJECT\TIA\PROD\mm
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Yudy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "algolia"
18 verbose node v9.3.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error yes@1.0.0 algolia: `atomic-algolia`
22 error Exit status 1
23 error Failed at the yes@1.0.0 algolia script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Dis I missed something?

**Comment by yudyananda** [comment]
Updating my `.env`  by removing the brackets

I dont know if it works but the error is gone

```
E:\YUDY\WEB PROJECT\TIA\PROD\mm>npm run algolia

> yes@1.0.0 algolia E:\YUDY\WEB PROJECT\TIA\PROD\mm
> atomic-algolia

(node:5572) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'concat' of undefined
    at E:\YUDY\WEB PROJECT\TIA\PROD\mm\node_modules\atomic-algolia\lib\utils\idsFromIndex.js:9:21
    at Array.reduce (<anonymous>)
    at idsFromIndex (E:\YUDY\WEB PROJECT\TIA\PROD\mm\node_modules\atomic-algolia\lib\utils\idsFromIndex.js:6:10)
    at calculateOperations (E:\YUDY\WEB PROJECT\TIA\PROD\mm\node_modules\atomic-algolia\lib\utils\calculateOperations.js:9:23)
    at E:\YUDY\WEB PROJECT\TIA\PROD\mm\node_modules\atomic-algolia\lib\update.js:32:34
    at <anonymous>
(node:5572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I wonder what causing the warning above

**Comment by yudyananda** [comment]
solved by get rid the backets in my `.env`
