### ISSUE TITLE
Cannot find module 'source-map-support/register'

### ISSUE THREAD

**Issue by DirtyF** [chrisdmacrae/atomic-algolia#13]
**Given** I update atomic-algolia package from `0.3.12` to `0.3.13`
**When** I run `npm run algolia`
**Then** the following error message is displayed:

```
> atomic-algolia

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/frank/code/jamstatic.fr/node_modules/atomic-algolia/lib/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by chrisdmacrae** [comment]
This should be fixed in `0.3.15`
